# Generated by Django 5.1.7 on 2025-03-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_subscriber_remove_article_image_remove_car_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
