# Generated by Django 5.1.7 on 2025-04-02 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0005_category_alter_article_image_url_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='category',
        ),
        migrations.RemoveField(
            model_name='car',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='car',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
    ]
