# Generated by Django 5.1.7 on 2025-04-10 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0006_remove_car_category_remove_car_condition_and_more'),
    ]

    operations = [
    ]
