# Generated by Django 5.1.7 on 2025-04-09

from django.db import migrations, models

def set_default_category(apps, schema_editor):
    Car = apps.get_model('autos', 'Car')
    Car.objects.filter(category__isnull=True).update(category='sedan')

class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0006_remove_car_category_remove_car_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(
                choices=[('sedan', 'Sedán'), ('suv', 'SUV'), ('sports', 'Deportivo'), ('pickup', 'Pickup')],
                default='sedan',
                max_length=50
            ),
        ),
        migrations.RunPython(set_default_category, reverse_code=migrations.RunPython.noop),
    ]
