# Generated by Django 5.1.7 on 2025-04-10 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0007_add_category_field_back'),
        ('autos', '0008_add_category_field_back'),
    ]

    operations = [
    ]
