# Generated by Django 5.2.4 on 2025-07-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0009_merge_20250409_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedán'), ('suv', 'SUV'), ('sports', 'Deportivo'), ('pickup', 'Pickup')], max_length=50, null=True),
        ),
    ]
